CREATE TABLE products(
type_id INT UNSIGNED NOT NULL, 
FOREIGN KEY(type_id)
REFERENCES product_type(id),
name VARCHAR(30) NOT NULL,
supplier VARCHAR(30) NOT NULL,
description BLOB NOT NULL,
id INT UNSIGNED NOT NULL 
AUTO_INCREMENT PRIMARY KEY);