CREATE TABLE item(
product_id INT UNSIGNED NOT NULL, 
FOREIGN KEY(product_id)
REFERENCES products(id),
size INT NOT NULL,#
colour VARCHAR(30) NOT NULL,
picture VARCHAR(256) NOT NULL,
price DECIMAL(6,2) NOT NULL,
id INT UNSIGNED NOT NULL 
AUTO_INCREMENT PRIMARY KEY);