CREATE TABLE sales_person(
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL, 
email VARCHAR(60) NOT NULL, 
street VARCHAR(50) NOT NULL, 
city VARCHAR(40) NOT NULL, 
state VARCHAR(2) NOT NULL,
zip MEDIUMINT UNSIGNED NOT NULL, 
phone_number VARCHAR(20) NOT NULL, 
birth_date DATE NULL, 
sex ENUM('M', 'F', 'OTHER') NOT NULL,
date_hired TIMESTAMP NOT NULL,
id INT UNSIGNED NOT NULL AUTO_INCREMENT
PRIMARY KEY);





